FROM node:10 AS runtime-stage

ENV TERM=xterm
ENV ROOT /var/www/app

WORKDIR $ROOT

COPY package*.json ./
RUN npm ci

# Only copy files in this folder with extensions
# This excludes directories that change frequently
# and are provided by docker volumes for development
COPY *.* ./

EXPOSE 4200

# --host=0.0.0.0 is required to access the server from outside of the docker container
# See https://stackoverflow.com/a/43492433/10530876
CMD npm run start -- --host=0.0.0.0 --disable-host-check
